### ISSUE TITLE
GNOME 3.38 at EOL

### ISSUE THREAD

**Issue by ozdreamern** [flathub/com.github.PintaProject.Pinta#17]
Time to update to base on GNOME 40?

> Info: org.gnome.Platform//3.38 is end-of-life, with reason:
>   The GNOME 3.38 runtime is no longer supported as of August 19, 2021. Please ask your application developer to migrate to a supported platform.
> Applications using this runtime:
>   com.github.PintaProject.Pinta

**Comment by darkdragon-001** [comment]
It is ready in [beta channel](https://github.com/flathub/flathub#using-the-flathub-repository) (see #16), but waiting for Pinta 1.8 to be released.
