### ISSUE TITLE
Please package Pinta 1.7.1 (feature request)

### ISSUE THREAD

**Issue by igor2x** [flathub/com.github.PintaProject.Pinta#21]
Yesterday Pinta 1.7.1 was released. Mainly a bug fix version, but very important to fix plenty of bugs. Also some new features available.
Release notes: https://www.pinta-project.com/releases/1-7-1

Could you please package Pinta 1.7.1 for flatpak version.

Note: I see Pinta 1.7.1 as snap package is already packaged: https://snapcraft.io/pinta so it would be nice to have flatpack package too.

**Comment by cameronwhite** [comment]
I submitted a pull request (#20) for this
